# Generated by Django 4.2 on 2025-01-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='transcription_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.course')),
            ],
        ),
    ]
