# Generated by Django 4.2 on 2025-01-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_uploadedpdf_uploadedvideo_uploadedcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
